spring.datasource.url=jdbc:postgresql://localhost:5432/ds_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Adicione esta linha para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update